# Generated by Django 5.1.2 on 2024-12-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.AlterField(
            model_name='project',
            name='media_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', max_length=500, null=True),
        ),
    ]
